### ISSUE TITLE
TryGetForm throws System.InvalidOperationException: 'Could not find the object with reference: 3 0.'

### ISSUE THREAD

**Issue by oleg-finka** [UglyToad/PdfPig#142]
This exception was originally thrown at this call stack:
	UglyToad.PdfPig.Tokenization.Scanner.PdfTokenScanner.Get(UglyToad.PdfPig.Core.IndirectReference)
	UglyToad.PdfPig.AcroForms.AcroFormFactory.GetAcroForm(UglyToad.PdfPig.Content.Catalog)
	UglyToad.PdfPig.PdfDocument..ctor.AnonymousMethod__0()
	UglyToad.PdfPig.PdfDocument.TryGetForm(out UglyToad.PdfPig.AcroForms.AcroForm)
    myFunction(string, bool, bool) in myCode.cs

It happens on opening attached file that contains form 
[wbg1.pdf](https://github.com/UglyToad/PdfPig/files/4258297/wbg1.pdf)

I'm doing this with this line
`bool hasForm = document.TryGetForm(out UglyToad.PdfPig.AcroForms.AcroForm form);`

**Comment by EliotJones** [comment]
Hi Oleg,

It looks like there's a problem with this document's format. Chrome opens it ok but Adobe Acrobat and Firefox have problems with it (Firefox displays it ok but the form isn't interactive). The object referenced by the AcroForm is genuinely missing.

If you have any contact with the document producer it's probably worth getting the document fixed because it will be incompatible with a lot of viewers.

I've added some code to handle the situation where the form is defined but missing. It now scans the whole file to reconstruct the form. I've attached a NuGet package with this fix to this comment, please give it a go and let me know how you get on.

[PdfPig.0.1.0-alpha002.zip](https://github.com/UglyToad/PdfPig/files/4262225/PdfPig.0.1.0-alpha002.zip)

**Comment by oleg-finka** [comment]
Hi Eliot,

Thanks for a quick answer! 
It parses only first page - is that ok? Anyway - it is better than nothing :)

**Comment by oleg-finka** [comment]
You absolutely right about file format. It would be better to fix its generation, but I really don't know how long could it take. So it is easier to find a good way to parse what we have :)

**Comment by oleg-finka** [comment]
About only first page - possibly I'm wrong. Seems it has text fields on page №1 and page №3 but they link to the same field. And if I change data in one place - it is changed in another automatically. That's why I see it only once in AcroForm. Thanks again!

**Comment by EliotJones** [comment]
Hi @oleg-finka , glad to hear you were able to retrieve the form content you needed. Is there anything else you need or can I close this issue now?
