### ISSUE TITLE
Strong naming the DLL

### ISSUE THREAD

**Issue by busbina** [UglyToad/PdfPig#158]
Can the dll be strong named? The lack of strong naming is blocking me using PdfPig as a nuget dependency.  I'm going to have to package up the dll's without it.

**Comment by busbina** [comment]
More than happy to do it my self, and pull request it. But I don't how the project wants to handle keys and singing.

**Comment by EliotJones** [comment]
Thanks for your issue. I must admit I'm not really familiar with strong naming, other than knowing it's a thing. I've had a bit of a read and I don't see any reason not to strong name it. Just to clarify, from what I read a strong named dll will work with code that doesn't use strong names, so adding a strong name helps people who need strong naming without causing problems for those who don't?

If that's the case I'm happy to go ahead and sign it. I had another question which I can't seem to find answers to in my brief search. PdfPig is made up of about 6 separate dlls, should each have its own key for strong naming or is a single key sufficient?

As far as managing keys goes the consensus seems to be the key is checked into the repository. Since strong-naming isn't really sufficient as a security measure I don't think there's a problem with checking in the private key (http://disq.us/p/1vo2391). It's most important that everyone is able to clone and build the code so making the key public seems the only way to ensure that and matches several other popular project's approach.

Let me know if I've misunderstood anything about strong-naming here because, as I say, it's not something I've had to work with before. If that's all fine then I'm happy to add it myself or accept a PR for strong naming.

**Comment by busbina** [comment]
Thanks for committing that! I'll verify every today (4/6).

**Comment by busbina** [comment]
Looks great, give it a test thanks!
