### ISSUE TITLE
Hightlight

### ISSUE THREAD

**Issue by ricardocduarte** [UglyToad/PdfPig#195]
Do we have any way to highlight texts ?

**Comment by EliotJones** [comment]
Hi @ricardocduarte, unfortunately PdfPig does not support this at the moment. In a PDF highlighting is a type of annotation. There is an issue outstanding to implement support for annotations https://github.com/UglyToad/PdfPig/issues/159. In the meantime you may be able to achieve what you need with PdfSharpCore https://github.com/ststeiger/PdfSharpCore.

At some point PdfPig will be updated to support editing existing documents #27 but I don't have any time to work on new features at the moment, sorry.

**Comment by SimantoR** [comment]
I actually need an alternative for PyMuPDF and this is perfect. Only thing that's missing is the annotation part. I'd be more than happy to contribute to it. I got it cloned and reading through it right now. But if you point me to something like trello and actually plan out what needs to be done, I can invest a day or so everyweek for it.

**Comment by EliotJones** [comment]
Hi @SimantoR thanks for your interest. I don't currently have anything like a roadmap but I'll try to put something together this coming weekend and we can go from there?

**Comment by SimantoR** [comment]
Sounds great. Also do let me know if there are code styles to follow and if they come with the repository

**Comment by SimantoR** [comment]
@EliotJones Any update on it? I might be able to provide 2 (including me) developers to the effort from my company.

**Comment by EliotJones** [comment]
Hi @SimantoR, sorry for not getting back to you, life has been hectic. In order to work out what the best way to approach this is, is your use-case to add highlights to existing documents or only for new documents created with PdfDocumentBuilder? In the case of new documents it's a fairly small project but if it's for existing documents then it may be considerably more work, because PdfPig doesn't currently have support for editing existing documents.
I may be moving country this coming weekend so my availability is limited for a bit longer, but I think once we know what the scope of the project should be we can create a GitHub project to track issues under. Thanks for your patience :)
