### ISSUE TITLE
Calculating the width of the space character for a given Font

### ISSUE THREAD

**Issue by Poltuu** [UglyToad/PdfPig#204]
I'm trying to write my own `IWordExtractor`, and I would like to find out the width of the space (" ") character for the font of a given `Letter`.

At first glance, it seems pretty tricky. I saw that you used your own method `Math.Max(lastLetter.GlyphRectangle.Height, letter.GlyphRectangle.Height) * 0.39` but I need to be more precise if possible.

Any idea ?

**Comment by InusualZ** [comment]
I think does number are an average approximation. Other than that, your best bet is to get the font from the letter and ask the font for the width of the space char. But I don't know If the API exist to retrieve a font

**Comment by BobLd** [comment]
Hi @Poltuu , I guess it would possible to extract this from the font data, maybe @EliotJones would be able to answer you on this point.

If you want to use the space width as part of a `IWordExtractor` implementation, I would be careful with it because it might not be as useful as it seems, for example in the case of _justified_ text (words can be closer or farther than 1 space). Also, some document actually print spaces characters, maybe you could use that as well (select all characters that are spaces in each page, and create a dictionary/group them according to font name and font size).

If you didn't, have a look at my [`NearestNeighbourWordExtractor`](https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig.DocumentLayoutAnalysis/WordExtractor/NearestNeighbourWordExtractor.cs). It should work in many cases. Any feedback is welcome. In this implementation, the maximum space allowed for 2 letters to be in the same word is 
```csharp
     double maxDist = Math.Max(Math.Max(Math.Max(Math.Max(Math.Max(
                    Math.Abs(l1.GlyphRectangle.Width),
                    Math.Abs(l2.GlyphRectangle.Width)),
                    Math.Abs(l1.Width)),
                    Math.Abs(l2.Width)),
                    l1.PointSize), l2.PointSize) * 0.2;
```

This can be modified by changing the `MaximumDistance` parameter of `NearestNeighbourWordExtractorOptions`.

**Comment by EliotJones** [comment]
Hi @Poltuu, as @BobLd and @InusualZ have mentioned the only fully accurate way to do this is use the font's specified whitespace character size if it contains one, however there will be scenarios where the font is only a subset of characters and does not contain the whitespace character.

Unfortunately there's currently no way available to check if a font contains a given character and get its dimensions if it does. Though it certainly sounds like a useful feature.

As @BobLd mentioned in the case of justified text there doesn't really exist a defined whitespace size and some document producers (including PdfPig I think) don't include the whitespace in the stream of text. I ran some analysis based on about 3000 documents from various sources and came up with a method based on best-fit of the data where the document contained a whitespace - https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Util/WhitespaceSizeStatistics.cs#L13 but again it's a fuzzy and inaccurate guess.

Another place it gets weird is some documents may have a center aligned title where the name is spaced out in all-caps, e.g:

```
                           G   R  A  N  T       P  R  O  P  O  S  A  L
Lorem ipsum etc...
```

So, again, unfortunately there's no precise measure for this stuff. I'll add a new feature flag to this and see if getting the size of an arbitrary unicode glyph from a document font is an easy addition.

**Comment by Poltuu** [comment]
Thank you all for your reactivity, I'll give a try to the NearestNeighbourWordExtractor.cs and play with the WhitespaceSizeStatistics to see if it's good enough in my scenario.

**Comment by BobLd** [comment]
Closed as answered - feel free to reopen if need be
