### ISSUE TITLE
Creating pdf document get font CapHeight

### ISSUE THREAD

**Issue by JanBN** [UglyToad/PdfPig#219]
Hello, 

I need to create pdf document and need font CapHeight so I can calculate some positions. I don't know how to get the cap height of the font. I thought using the FontDescriptor, but I can not get the FontDescriptor either. 

This is how I get the font
```
 var font = builder.AddTrueTypeFont(File.ReadAllBytes(trueTypeFontPath));
``` 
It gives me something called AddedFont which has nothing usefuel in it.

Thank you for any help.

**Comment by EliotJones** [comment]
Hi, `PdfDocumentBuilder` doesn't currently surface this information because it would be extra maintenance for the public API while the design of font parsing isn't set, however you can use the underlying TrueType parser the builder uses to extract the font information as follows:

```
var file = File.ReadAllBytes(trueTypeFontPath);
var ttf = TrueTypeFontParser.Parse(new TrueTypeDataBytes(file));
if (ttf.TableRegister.Os2Table is Os2Version2To4OpenTypeTable os2)
{
    var capHeight = os2.CapHeight;
}
```

It's been a while since I've done any font related work but it looks like only OS table versions 2+ have the cap height property. Let me know if this works ok :)

**Comment by JanBN** [comment]
Yes this did work. Thank you.
