### ISSUE TITLE
Issue with recognizing 2 letters as 1

### ISSUE THREAD

**Issue by Smurfj3** [UglyToad/PdfPig#226]
So basically I extract all words of a PDF, I noticed 1 word letters have 1 Letter that has as value 2 letters in it. There is plenty of other words on the PDF with the same Font and Font size that don't have the issue but this 1 specific word does. Again an issue that has only happened to me once over the last 1000 pdf's, it's no a big deal but figured I'd report it.

**Comment by BobLd** [comment]
Hi @Smurfj3 , can you give more details regarding what you want to achieve? why is it an issue? having two letters in one character is quite common. My guess is that you have a [ligature](https://en.wikipedia.org/wiki/Orthographic_ligature).

An example of ligature: f‌i | ﬁ (the second is a single character).

**Comment by Smurfj3** [comment]
Aw yes, it happened to be fi indeed, I rather had them separate but oh well. Thanks for the reply!

**Comment by BobLd** [comment]
Fyi, if you to split the two characters in the string, you can use `value.Normalize(NormalizationForm.FormKD);` (more info [here](https://docs.microsoft.com/en-us/dotnet/api/system.string.normalize?view=netcore-3.1)). But you will still have a single bounding box.

**Comment by EliotJones** [comment]
I'm going to close this one now, I think it's better to leave separation of ligatures as a user-implemented post-processing step since the letters content of the page should be as close as possible to the raw PDF content. If you need 2 bounding boxes I'd suggest just creating 2 rectangles of 1/2 the width of the ligature bounding box, it won't be exact but should be good enough, hopefully.
