### ISSUE TITLE
font dictionary did not have a /FirstChar - error recurs for different fonts

### ISSUE THREAD

**Issue by FAC-jAH** [UglyToad/PdfPig#239]
I guess I spoke too soon.  #236 is fixed for that sample file.
Turns out I have several other examples I assumed were the same error _"UglyToad.PdfPig.Fonts.InvalidFontFormatException: The provided TrueType font dictionary did not have a /FirstChar and did not match a Standard 14 font:"_
but it appears that the other occurrences in other files have different fonts causing the issue:
<FontDescriptor, 13 0>, <BaseFont, /Tahoma-Bold,Bold>
<FontDescriptor, 134 0>, <BaseFont, /Tahoma>

Unfortunately the files with these specific font failures are not certified as having no PII, so I can't share those other examples.

**Comment by EliotJones** [comment]
Sorry to hear you're still encountering issues. If you are able to would you be able to provide the full font dictionary and the font descriptor details. You can open the PDF in Notepad++ or similar and copy the content out as plain text. It will look something like this for the font dictionary:

```
120 0 obj
<</Type/Font /FontDescriptor 13 0 R /BaseFont /Tahoma-Bold>>
endobj
```

And the font descriptor would be something like:

```
13 0 obj
<< [dictionary-contents...] >>
endobj
```

Though the number 120 will be different for your documents.

Since these dictionaries don't contain any content information it should be safe to include them here without any PII.

I looked into it and no-one seems to have encountered using Tahoma as a standard 14 font so I think I might be missing some important step for handling these dictionaries. It sounds like previously Adobe has expected these fonts to be provided by the OS so it might be the case that's what's going on but it's difficult to tell at the moment.

**Comment by FAC-jAH** [comment]
The Font blocks were scattered all over the file, I think this is all of them.
[FontElements_pdf_22641320172.txt](https://github.com/UglyToad/PdfPig/files/5618082/FontElements_pdf_22641320172.txt)

The SME will be back tomorrow, I will work with him to locate more 'safe' examples.

**Comment by EliotJones** [comment]
Thanks, that's very helpful, I'll try and have a look in the next couple of days.

**Comment by EliotJones** [comment]
Wasn't able to get anywhere without a file for reference
