### ISSUE TITLE
Error in using GetPage() 

### ISSUE THREAD

**Issue by honeyhead** [UglyToad/PdfPig#241]
{"Could not find the referenced CMap: Adobe-Korea1-3"}

I don't think I can read the specific font included in the PDF.
How can I read it in this case? I've read about Parser, but I don't know how.

Perhaps you won't be able to read Japan or any other foreign language besides "Adobe-Korea1-3.

**Comment by honeyhead** [comment]
Is there any way to extract font?

**Comment by UE4Thommie** [comment]
I had a similar issue with the Adobe-Japan1-7 CMap, which I added manually to \src\UglyToad.PdfPig\Resources\CMap\ after which the problem was solved.

I obtained this CMap from [https://github.com/adobe-type-tools/cmap-resources/](url). It seems Korea1-3 is not in there, but possibly it would work with those in the Adobe-KR-9 folder.

**Comment by EliotJones** [comment]
Closing this since I think it has been fixed, let me know if you encounter any issues.
