### ISSUE TITLE
measurement properties

### ISSUE THREAD

**Issue by simonedd** [UglyToad/PdfPig#276]
Hello,

Is there a way to get the measurement properties, as described in chapter 8.8 in the PDF Reference document? Thanks.

**Comment by EliotJones** [comment]
Hi @simonedd currently there's no built in support for this, the information can be accessed via the `Page.Dictionary` property as follows:

```
if (document.GetPage(1).Dictionary.TryGet(
    NameToken.Create("VP"),
    out ArrayToken viewPortsArray))
{
    foreach (var entry in viewPortsArray.Data)
    {
        if (entry is DictionaryToken viewPortDictionary)
        {
            if (viewPortDictionary.TryGet(NameToken.Create("Measure"), out DictionaryToken measureDictionary))
            {
                // etc...
            }
        }
    }
}
```

I'm labelling this `good first issue` since building a useful API for this shouldn't be too hard, e.g. `page.Experimental.GetViewports()` and mainly involves wrapping calls in the indirect reference safe `dictionaryToken.TryGet(NameToken, IPdfTokenScanner, out T token) where T : IToken` methods used internally to safely look up dictionary entries.
