### ISSUE TITLE
Letter GlyphRectangle with Height == 0

### ISSUE THREAD

**Issue by simonedd** [UglyToad/PdfPig#287]
Hi,

In this document, all the letters have a GlyphRectangle with a Height equals to zero.
[A1-RU-101-S.pdf](https://github.com/UglyToad/PdfPig/files/5956725/A1-RU-101-S.pdf)

**Comment by BobLd** [comment]
Hi @simonedd, have you tried compiling and testing this document with the current master? Some fixes have been push to fix bbox height recently - but your document might be another case of this issue

**Comment by simonedd** [comment]
Yes, I tested with the latest version.

**Comment by BobLd** [comment]
The issue comes from the `Type0CidFont` class (in `UglyToad.PdfPig.PdfFonts.CidFonts`).

I've added the following property `private readonly double scale;` that is set in the constructor:
`scale = 1 / (double)(fontProgram?.GetFontMatrixMultiplier() ?? 1000);`


Then in the `GetBoundingBox(int characterIdentifier)` function I've amended the code as follow:


![image](https://user-images.githubusercontent.com/38405645/107854301-f1323c00-6e12-11eb-8c13-3e41459f070a.png)

**Comment by BobLd** [comment]
closed as fixed in 0.1.5
