### ISSUE TITLE
PdfPig is seeing a hyphen as a "plus-minus" symbol?

### ISSUE THREAD

**Issue by ZukkyBaig** [UglyToad/PdfPig#289]
Hi,

When I use PdfPig to extract text from a PDF as follows: "Monday-Friday", it extracts it as: "Monday±Friday". I'm not sure why this is happening?

Is there a way of setting in PdfPig to treat a "plus-minus sign" as a hyphen?

![bug](https://user-images.githubusercontent.com/20065329/107804878-6c84e680-6d5c-11eb-9191-32a3b5c70b22.png)

**Comment by EliotJones** [comment]
Hi @ZukkyBaig,

Without access to the document it's hard to tell what's happening here. If you copy the text using a viewer like Chrome/Adobe does the text also come out as a +/- sign? In that case it's a problem with the document rather than PdfPig and you'd have to encode some custom rules to handle it.
