### ISSUE TITLE
Block/lines

### ISSUE THREAD

**Issue by christopher5106** [UglyToad/PdfPig#295]
On page 3 of the following document:
https://drive.google.com/file/d/1K0C-VhHrrSHes6STGRtNj1vPRfDmcW1l/view?usp=sharing

I get with the following code:
```
var words = page.GetWords(NearestNeighbourWordExtractor.Instance).ToList();
var blocks = DocstrumBoundingBoxes.Instance.GetBlocks(words);
var orderedBlocks = new UnsupervisedReadingOrderDetector(spatialReasoningRule: UnsupervisedReadingOrderDetector.SpatialReasoningRules.RowWise, useRenderingOrder: false).Get(blocks).ToList();
var finalBlocks = new List<UglyToad.PdfPig.DocumentLayoutAnalysis.TextBlock>(orderedBlocks);
```

the following blocks:

- The Sicav’s board of directors (hereinafter the "Board of Directors") is responsible for the accuracy of the information contained in the current Prospectus on the date of its publication. Consequently, any information or affirmation not contained in the Prospectus, the appendices to Part II of the Prospectus if appropriate, or in the reports which form an integral part of it must be considered as unauthorised.
- that
- potential
- subscribers
- This Prospectus is subject to updates. Therefore its is recommended enquire at the Sicav about the publication of the most recent Prospectus.

Which is not what a human would read, in particular in this case it should be only one block 
- This Prospectus is subject to updates. Therefore its is recommended that potential subscribers
enquire at the Sicav about the publication of the most recent Prospectus.

This error is not isolated, thought it is classical. For example in the following document, the last 4 blocks are :

https://drive.google.com/file/d/17ciCAISAhzlw6rjt3ZCWqBpXQEtRPpdo/view?usp=sharing

- IF YOU ARE IN ANY DOUBT ABOUT THE CONTENTS OF THE PROSPECTUS YOU SHOULD STOCKBROKER, YOUR CONSULT ACCOUNTANT OR OTHER FINANCIAL ADVISER.
- BANK
- MANAGER,
- SOLLICITOR,

**Comment by BobLd** [comment]
Hi @christopher5106,

Regarding your 1st document, could you check with the latest version of PdfPig?
I did layout extraction and it seems blocks are correctly formed:
![image](https://user-images.githubusercontent.com/38405645/129746387-93ce8562-fefa-4f63-b210-757ff27b22f7.png)

Regarding the 2nd document, the problem remains:
![image](https://user-images.githubusercontent.com/38405645/129746241-3103b2ca-3930-4bc0-9e7c-faa0379a8175.png)

The problem comes from the line detection step - the lines are not crrectly formed:
![image](https://user-images.githubusercontent.com/38405645/129746740-dd65b7bc-17b5-43dc-8494-4a7116207d0f.png)

My guess is that the text being justified and in upper case, the spaces between the words are too large which prevent lines to be correctly formed. My advice is to play around with the docstrum algo parameters, especially the `BetweenLineMultiplier`, see here: 
https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#advanced-case-1

Another approach would be to use the `RecursiveXYCut` algo instead of the Docstrum one:
```csharp
var words = page.GetWords(NearestNeighbourWordExtractor.Instance).ToList();
var blocks = RecursiveXYCut.Instance.GetBlocks(words);
var orderedBlocks = new UnsupervisedReadingOrderDetector(spatialReasoningRule: UnsupervisedReadingOrderDetector.SpatialReasoningRules.RowWise, useRenderingOrder: false).Get(blocks).ToList();
var finalBlocks = new List<UglyToad.PdfPig.DocumentLayoutAnalysis.TextBlock>(orderedBlocks);
```
Result with RecursiveXYCut:
![image](https://user-images.githubusercontent.com/38405645/129748002-3b3e0d83-68ee-411a-baca-8724863db10d.png)

**Comment by BobLd** [comment]
Closing as answered - feel free to reopen if need be
