### ISSUE TITLE
Extract math characters?

### ISSUE THREAD

**Issue by Bia10** [UglyToad/PdfPig#330]
Is there any way to properly extract math characters?

Lets say i want to extract following sentence:

![image](https://user-images.githubusercontent.com/2548763/118480636-cd80d980-b712-11eb-840d-2750fa29988e.png)

The result is something like this:

![image](https://user-images.githubusercontent.com/2548763/118480797-ff923b80-b712-11eb-8b34-08540ad2cd20.png)

generally I have noticed that the extraction is very clumsy on superscripts, subscripts, commas and other typograhical marks

**Comment by EliotJones** [comment]
Hi there, if you copy and paste the text from a PDF viewer such as Google Chrome or similar do you get the expected output? If so are you able to share and example file please?

**Comment by Bia10** [comment]
What I was hoping to obtain was information relating to capabilities of pdfpig as I have not read the src I don't know what its capable of.

Are there any possibilities of custom text extraction strategies like in iText? a horizontal extraction could solve the subscript, superscript problems.

If the latex symbols cannot be parsed fair enough however still if at least the bounding box of the symbols is correct then we could render the pdf page via PDFiumSharp or Pdf2png and capture screen on these symbols and send them to OCR.

the correct output would be:
```
{\square,}
{\bigcirc,}
{\mathbb{T}}
```

**Comment by EliotJones** [comment]
So the problem is PDFs do not preserve Latex information at all. They are under no specification obligation to preserve semantic meaning of text for any generation method. Without access to the source document I can't really tell if what PdfPig generates here is wrong or just what is present in the PDF content. There's more information about the bounding boxes in the wiki https://github.com/UglyToad/PdfPig/wiki/Letters but guessing from your question it sounds like those bounding boxes are incorrect?

More details about PDFs and their loose relation to source text here https://dev.to/eliotjones/reading-a-pdf-in-c-on-net-core-43ef

**Comment by Bia10** [comment]
Okay, I guess ill have to read to source, your constantly redirecting to information I know already rather then proving an actual answer.

**Comment by sir-deenicus** [comment]
> Are there any possibilities of custom text extraction strategies like in iText? a horizontal extraction could solve the subscript, superscript problems.

This is something that seems like it should be straightforward but isn't. It's difficult to do in a robust manner due to the long tail of pdfs that do really weird things. But it might be worth looking into:  https://github.com/BobLd/DocumentLayoutAnalysis for a starting point?

> If the latex symbols cannot be parsed fair enough however still if at least the bounding box of the symbols is correct then we could render the pdf page via PDFiumSharp or Pdf2png and capture screen on these symbols and send them to OCR.

This doesn't really fall under the purview of a pdf parsing library, it should be an addon library akin to the one linked above. Also, there is no free OCR solution able to compute image to latex. The best is mathpix but again, is not free. Building such a library would be an intense undertaking requiring computer vision and deep learning.

**Comment by BobLd** [comment]
Have a look here to check how it's currently implemented in the library:
https://github.com/UglyToad/PdfPig/tree/master/src/UglyToad.PdfPig.DocumentLayoutAnalysis
