### ISSUE TITLE
Digital Signature details

### ISSUE THREAD

**Issue by jbrou015** [UglyToad/PdfPig#357]
Hi. This is not an issue. I am trying to get information about digital signatures. When a PDF document has signatures I can see it from AcroForm and AcroFormField. However my question is: how can I get details about a signature. I would like to know who signed and when. Any help would be appreciated. Thanks

![image](https://user-images.githubusercontent.com/47859593/128866524-3db58d58-9b2f-4ae8-8839-435ddafcb2b6.png)

**Comment by EliotJones** [comment]
Hi there, it looks like if you expand the `Dictionary ` property of the `field` it should contain a field called `V` according to the spec. This contains a whole bunch of data about the signature we don't currently have the API to process.

![image](https://user-images.githubusercontent.com/7862346/129122446-4668efe0-fc34-4b51-a8a9-223d9fbebf97.png)

You will probably need to use the get object method since the value dictionary is likely to be a reference to another object, e.g:

```
if (field.TryGet(NameToken.V, out var valueToken))
{
    if (valueToken is DictionaryToken valueDictionary)
    {
        // Get the fields normally.
    }
    else if (valueToken is IndirectReferenceToken valueReferenceToken)
    {
        var linked = document.Structure.GetObject(valueReferenceToken.Data);

        if (linked.Data is DictionaryToken referencedValueDictionary)
        {
            // Get the fields normally
        }
    }
}

```

**Comment by rajasekarshanmugam** [comment]
@jbrou015 did you get any breakthrough on this? I don't see V value, but a bunch of others. Trying to lookup each property to see if can get any information, but so far none.

![image](https://user-images.githubusercontent.com/5011723/149743098-aab66a2a-b642-464f-b73e-2b5dc38e51ee.png)

**Comment by jbrou015** [comment]
I ended up using iText7 for this. The unlimited version of iText7 was providing me with everything I needed.

**Comment by EliotJones** [comment]
Ok, closing this then. A better API could be part of a rework of forms API if anyone wants to try it in future.
