### ISSUE TITLE
Some text is missing

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#48]
For attached PDF the charts and text around them are missing. For example the text "Historical Arrears by Month" is not in Letters collection or page extracted text, as well as all the numbers/labels on the charts. The lines (paths collection) are also missing everything around the charts area. Is there possibly a sub-stream, which is not being processed?

[missing_text_sample.pdf](https://github.com/UglyToad/PdfPig/files/3429352/missing_text_sample.pdf)

**Comment by EliotJones** [comment]
Thanks for the bug report. This might be due to the text being in forms rather than content, I'll take a look this weekend.

**Comment by EliotJones** [comment]
Sorry it took so long to get round to this, I need a holiday! 😆 

This actually turned out to be a fairly major bug in how PdfPig was handling content streams so it's a good thing to fix. Please try out the latest build and it should work for this document 🤞 

I've moved `PdfPath` back to `Page.ExperimentalAccess` for now because I'm about to make a release and want to add color support to paths before making them a fixed member of the public API.

**Comment by vadik299** [comment]
Thank you Eliot! I will test the new release. Lots of good stuff there! Thanks again!

Color support would be very useful. Are you planning to add it to letters too?

**Comment by EliotJones** [comment]
> Color support would be very useful. Are you planning to add it to letters too?

Yes, initially the plan is to add support for CMYK, RGB and Grayscale colorspaces to both letters and paths. There's some more complexity in color for PDFs when it comes to patterns and CIE colors and whatnot but for now I'll try and get the most common color types implemented.

**Comment by EliotJones** [comment]
Did the latest version fix this issue? I'm just going through tidying up the issues and hopefully this can be closed 🤞.

**Comment by vadik299** [comment]
Yes, fixed. Thank you!
