### ISSUE TITLE
Exception reading some images from PDF file

### ISSUE THREAD

**Issue by ilCosmico** [UglyToad/PdfPig#489]
The attached file contains a lot of images that cannot be read due to the below exception:

![image](https://user-images.githubusercontent.com/8678145/188860377-16998df1-606e-41dc-bfec-19cbf12a20ac.png)

I started from [your sample code](https://github.com/UglyToad/PdfPig/blob/master/examples/ExtractImages.cs) and I just add the code for saving bmp file.

```
using System;
internal static class ExtractImages
{
    public static void Run(string filePath)
    {
        using (var document = PdfDocument.Open(filePath))
        {
            foreach (var page in document.GetPages())
            {
                foreach (var image in page.GetImages())
                {
                    if (!image.TryGetBytes(out var b))
                    {
                        b = image.RawBytes;
                    }

                    var type = string.Empty;
                    switch (image)
                    {
                        case XObjectImage ximg:
                            type = "XObject";
                            break;
                        case InlineImage inline:
                            type = "Inline";
                            break;
                    }

                    Console.WriteLine($"Image with {b.Count} bytes of type '{type}' on page {page.Number}. Location: {image.Bounds}.");

                    try
                    {
                        Image im = Image.FromStream(new MemoryStream(b.ToArray()));

                        string filename = "test.bmp";
                        if (File.Exists(filename))
                            File.Delete(filename);
                        im.Save(filename);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        
                    }
                }
            }
        }
    }
}
```
Can this be fixed in some way, please?

[Test2.pdf](https://github.com/UglyToad/PdfPig/files/9505447/Test2.pdf)

**Comment by fnatzke** [comment]
Thank you @ilCosmico.   
For image of type XObject please use **TryGetPng** rather than **TryGetBytes**.

Below is an update example:
`namespace UglyToad.Examples
{
    using System;
    using PdfPig;
    using PdfPig.Content;
    using PdfPig.XObjects;

    using MemoryStream = System.IO.MemoryStream;
    using File = System.IO.File;
    using Directory = System.IO.Directory;
    using Path = System.IO.Path;
    using System.Linq;
    internal static class ExtractImages
    {
        public static void Run(string filePath)
        {
            var outputPath = @"c:\temp\PhpPig";
            if (Directory.Exists(outputPath) == false) { Directory.CreateDirectory(outputPath); }   
            using (var document = PdfDocument.Open(filePath))
            {
                foreach (var page in document.GetPages())
                {
                    var i = 0;
                    foreach (var image in page.GetImages())
                    {
                        i++;
                        byte[] ab = new byte[0];

                        var type = string.Empty;
                        switch (image)
                        {
                            case XObjectImage ximg:
                                type = "XObject";
                                if (!image.TryGetPng(out ab))
                                {
                                    if (!image.TryGetBytes(out var ax))
                                    {
                                        ax = image.RawBytes;
                                    }
                                    ab = ax?.ToArray();
                                }
                                break;
                            case InlineImage inline:
                                type = "Inline";
                                if (!image.TryGetBytes(out var ai))
                                {
                                    ai = image.RawBytes;
                                }
                                ab = ai?.ToArray();
                                break;
                        }

                        Console.WriteLine($"Image {i} with {ab.Length} bytes of type '{type}' on page {page.Number}. Location: {image.Bounds}.");

                        try
                        {
                            var outputFilePath = Path.Combine(outputPath,$@"test{i}.png");
                            if (File.Exists(outputFilePath))
                                File.Delete(outputFilePath);
                            File.WriteAllBytes(outputFilePath, ab);
                        }
                        catch (Exception e)
                        {
                            Console.WriteLine(e);
                        }
                    }
                }
            }
        }
    }
}
`

Found 17 images in test2.pdf supplied.

`Image 1 with 36643 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:697.53), 479.88, 30.1799999999999].
Image 2 with 32527 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:667.35), 479.88, 30.1799999999999].
Image 3 with 25269 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:637.17), 479.88, 30.1799999999999].
Image 4 with 40961 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:606.99), 479.88, 30.1799999999999].
Image 5 with 68562 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:576.81), 479.88, 30.1799999999999].
Image 6 with 66052 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:546.63), 479.88, 30.1799999999999].
Image 7 with 65267 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:516.45), 479.88, 30.1799999999999].
Image 8 with 52512 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:486.27), 479.88, 30.18].
Image 9 with 48224 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:456.09), 479.88, 30.18].
Image 10 with 48610 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:425.91), 479.88, 30.18].
Image 11 with 36777 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:395.73), 479.88, 30.18].
Image 12 with 30276 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:365.55), 479.88, 30.18].
Image 13 with 21218 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:335.37), 479.88, 30.18].
Image 14 with 29092 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:305.19), 479.88, 30.18].
Image 15 with 29513 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:275.01), 479.88, 30.18].
Image 16 with 23303 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:244.83), 479.88, 30.18].
Image 17 with 17509 bytes of type 'XObject' on page 1. Location: [(x:74.7, y:214.65), 479.88, 29.88].
`

**Comment by EliotJones** [comment]
Thanks @fnatzke for the answer here. I'm closing this since I believe this is resolved
