### ISSUE TITLE
Print Character with ZapfDingbats font

### ISSUE THREAD

**Issue by rwest500** [UglyToad/PdfPig#514]
The font metric file for ZapfDingbats does not have standard character names:
See:  "UglyToad.PdfPig.Fonts.Resources.AdobeFontMetrics.ZapfDingbats.afm"

This causes the pdf page builder to fail when using AddText (Is there an alternate for non standard encodings?)
See simple case farther below:

I've fixed it with a modification to look up character metrics by code instead of name here:
UglyToad.PdfPig.Writer.Fonts.Standard14WritingFont.TryGetBoundingBox(..)
it probably not the best way but it works.

//------------------  Fix if using special character set then look up by code when not found by name
       public bool TryGetBoundingBox(char character, out PdfRectangle boundingBox)
        {
            var encoding = StandardEncoding.Instance;
            boundingBox = default(PdfRectangle);
            
            if (!metrics.CharacterMetrics.TryGetValue(encoding.GetName(character), out var characterMetric))
            {
                bool found = false;
                if (metrics.CharacterSet == "Special")
                {
                    foreach( var ch in metrics.CharacterMetrics)
                    {
                        if (ch.Value.CharacterCode == character)
                        {
                            characterMetric = ch.Value;
                            found = true;
                            break;
                        }
                    }
                }
                if (!found)
                {
                    return found;
                }
            }

            boundingBox = new PdfRectangle(characterMetric.BoundingBox.Left, characterMetric.BoundingBox.Bottom,
                characterMetric.BoundingBox.Left + characterMetric.Width.X, characterMetric.BoundingBox.Top);

            return true;
        }

//-----------------------------------------------------------

Simple Case Example: 
PdfDocumentBuilder builder = new PdfDocumentBuilder();
PdfDocumentBuilder.AddedFont wdFont = builder.AddStandard14Font(Standard14Font.ZapfDingbats);
PdfPageBuilder page =builder.AddPage(PageSize.A4);

double topPageY = page.PageSize.Top - 50;
double inch = (page.PageSize.Width / 8.5);
double cm = inch / 2.54;
double leftX = 1 * cm;

PdfPoing nextPoint = new PdfPoint(leftX, topPageY);
page.AddText("v", 12, nextPoint, wdFont); // threw an exception the standard character name "V" not in ZapfDingbats

**Comment by fnatzke** [comment]
@rwest500 and @EliotJones, working on this. Seem to have a working solution. Testing.

**Comment by fnatzke** [comment]
[ZapfDingbatsFontAddText.pdf](https://github.com/UglyToad/PdfPig/files/10214328/ZapfDingbatsFontAddText.pdf)
@rwest500 and @EliotJones completed testing. 

Attached is example PDF generated with update library with all ZapfDingbats characters.

Fixes:
1. ZapfDingbatsEncoding.cs Codes in ZapfDingbats EncodingTable not converted (like in StandardEncoding.cs).   C# (soure code  .cs file) has code with a leading '0' (zero) intended as octal (base 8) int litteral but parsed as base10. (C# does not support octal int letterls).
2.  Standard14WritingFont.cs Writer using MacRomainEnoding rather than font specific encoding for ZapfDingbats (and Symbol) font(s) (and Standard encoding for the 12 other Adobe Standard Fonts).
3.  In Standard14WritingFont.cs Methods TryGetBoundingBox and GetValueForCharacter attempt to use MacRomainEnoding glyth names rather than font specific encoding.
