### ISSUE TITLE
Exception: Could not find the version header comment at the start of the document

### ISSUE THREAD

**Issue by pramodh2712** [UglyToad/PdfPig#543]
Hi, I am trying to read the one of the PDF but I receive the below error. 

Exception: Could not find the version header comment at the start of the document

I am using pdfpig version (0.1.8-aplha), I see this is solved in the past but not sure if this is missing in the version I am using.  Please check the below code that I use. 

```
public int ExtractText(byte[] document, Dictionary<int, string> content)
        {
            var pageCount = 0;

            try
            {
                using var pdfDocument = PdfDocument.Open(document); //  I am getting the error at this line. 

                foreach (var pg in pdfDocument.GetPages())
                {
                    content.Add(pageCount, ContentOrderTextExtractor.GetText(pg, true));
                    pageCount++;
                }
            }
         
            catch (Exception exception)
            {
                throw HandleGeneralException(exception);
            }

            return pageCount;
        }
```

**Comment by fnatzke** [comment]
@pramodh2712, Thank you for reaching out. Your code looks fine. Seems like is a problem with the file. Could you attach an example PDF that created the error please?

**Comment by pramodh2712** [comment]
> @pramodh2712, Thank you for reaching out. Your code looks fine. Seems like is a problem with the file. Could you attach an example PDF that created the error please?

@fnatzke Please check the attached sample file which has issues. 
 
[Sample file.PDF](https://github.com/UglyToad/PdfPig/files/10519881/Sample.file.PDF)

**Comment by fnatzke** [comment]
This is what I found.

Using the sample PDF file able to open (uisng PdfDocument.Open with filepath) without an exception using PdfPig version 0.1.8-alpha-20230117-88aad,

Did get an exception GetPage(pageNumber) due to a missing font but can be suppressed using SkipMissingFonts option with ParsingOptions on PdfDocument.Open as follows:

        var parsingOptions = new ParsingOptions();
        parsingOptions.SkipMissingFonts = true;

        using (var pdfDoc = PdfDocument.Open(filePathOrig, **parsingOptions**))

Note: second argument to Open( ... , parsingOptions)

Full working demo app (.Net7 Console App) attached in 543.zip
[543.zip](https://github.com/UglyToad/PdfPig/files/10526561/543.zip)

Demo app is self contained and includes C# source code, Visual Studio Project, Visual Studio Solution with the 5 required PdfPig projects directly included as dependants (rather than through NuGet) with their source in a peer subfolder (..\pdfpig):
    UglyToad.PdfPig
    UglyToad.PdfPig.Core
    UglyToad.PdfPig.Fonts
    UglyToad.PdfPig.Tokenization
    UglyToad.PdfPig.Tokens

Note to get text I didn't use ContentOrderTextExtractor but just straight page.Text.

Screenshot of demo app output:

![Screenshot-DemoApp-Output](https://user-images.githubusercontent.com/15922731/215252871-3d50bffa-9b53-4889-8544-799057f6f7b0.png)

@pramodh2712 this sample file (Sample.File.PDF) did not seem to exhibit the ('open') issue. 
I note your original source using a byte stream ( byte[]  ) rather than file path ( string ).
Perhaps if you could send another sample file for testing please.

**Comment by EliotJones** [comment]
This exception message `Exception: Could not find the version header comment at the start of the document` indicates the provided bytes did not actually contain the bytes of a PDF file, as mentioned you can either use the file path directly or ensure you are correctly populating the bytes provided in the `document` variable in your example code.
