### ISSUE TITLE
BoundingBox for Images

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#55]
Hi,

Unless I am mistaken, there is no support for getting an image's BoundingBox. Is there any plan to add this functionality?

Thanks!

**Comment by EliotJones** [comment]
That's correct, at the moment the existing image functionality is very basic and not particularly useful.

It's certainly something I want to improve and since you've requested it I'll look into how much work it's going to be.

I'm currently adding colors for fonts and paths and hopefully sub-setting for TrueType font for document creation purposes (to reduce the size of documents created with PdfPig) but it could be another feature candidate for 0.0.9 (the next release).

**Comment by BobLd** [comment]
That's perfect! Thanks

**Comment by EliotJones** [comment]
The images API should now be improved. To enumerate all images on a page you can call `page.GetImages()`.

This returns a list of `IPdfImage` which is one of `InlineImage` or `XObjectImage`. Each `IPdfImage` has a `Bounds` property which corresponds to the placement rectangle on the page. The properties `WidthInSamples` and `HeightInSamples` are unrelated to the width or height of the image within the document (they correspond to the original size of the image as created).

I'll close this issue for now but let me know how you get on with the new API. (Note that calling `image.Bytes` can/will throw for most images but I don't think there's a need to access them currently).
