### ISSUE TITLE
Document metadata/XMP access?

### ISSUE THREAD

**Issue by Numpsy** [UglyToad/PdfPig#57]
Hi,

Any plans or thoughts about adding a direct means of getting the XMP metadata of a document?
Looks like I can get hold of the data by doing something like

```
doc.Structure.Catalog.CatalogDictionary.TryGet<IndirectReferenceToken>(NameToken.Metadata, out var token);

var objectToken = doc.Structure.GetObject(token.Data);
var streamToken = objectToken.Data as UglyToad.PdfPig.Tokens.StreamToken;
```

and then parsing streamToken.Data with XmpCore, but it might be useful to be able to get at the data more directly (not sure what the best format to expose it as would be though).

**Comment by EliotJones** [comment]
I've added a method to `PdfDocument` to get the wrapped metadata stream, this gives you access to both the raw pdf token and the decoded stream data (where any encryption or filters are applied).

The method is `PdfDocument.TryGetXmpMetadata(out XmpMetadata metadata)` and there is an example of usage here: https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig.Tests/Integration/LaTexTests.cs#L130

I'd be interested in feedback/ways to improve this because I'm not familiar with typical use-cases for this data so if it could be easier to consume I'd be happy to make those changes.

I've attached a NuGet package with this change in.

[PdfPig.0.0.7.57.zip](https://github.com/UglyToad/PdfPig/files/3489916/PdfPig.0.0.7.57.zip)

**Comment by Numpsy** [comment]
Thanks, I'll give it a test later.

I was looking at it because one of the projects I work on can use XMP to store custom meta data in various types of files (in the case of PDF, you can use the XMP data instead of or on top of custom entries in the document information).
As far as APIs go, the lib that uses is built on the Adobe (C++) XMP SDK, and I was just testing with the [C# port of that](https://github.com/drewnoakes/xmp-core-dotnet). That lib can use both a byte[] and an XDocument as an input, so if reading the XDocument directly isnt sufficient that's still a useful format to consume.

**Comment by Numpsy** [comment]
On a related note though, section 14.3.2 of the (PDF32000) spec says

```
The metadata framework provides a date stamp for metadata expressed in the  framework.  If  this  date  stamp  is  equal  to  or  later  than  the  document  modification  date  recorded  in  the  document  information  dictionary...
```

So perhaps it would be useful if the modification date were directly exposed though DocumentInformation in order to check?

**Comment by EliotJones** [comment]
Good point, I read that in my version as being specific to backwards compatibility for pre 1.4 versions of PDF but I probably misunderstood it. Either way it's useful information to expose.

**Comment by EliotJones** [comment]
Apologies for the long delay with this but I think the API should now have everything you need, or is there an additional date field on the XMP dictionary that needs to be exposed to perform the check in 14.3.2?

**Comment by Numpsy** [comment]
Thanks for the changes.
I can get the date fields out of the the Xml/Xmp data directly ok, which is fine for what i'm doing with it.

**Comment by EliotJones** [comment]
Thanks, I'll close this for now then, let me know if you run into any more missing API in future for any metadata related stuff.
