### ISSUE TITLE
Using the default word detector doesn't change the Y value.

### ISSUE THREAD

**Issue by johnsharp1975** [UglyToad/PdfPig#603]
The default word detector _y_ variable only appears to be set during the first loop.

There's a paragraph starting "if (letter.Location.Y > " which doesn't look like it can ever be true because the discovered letters are in the opposite order to that which is checked for.

I've made two amendments to a local version of the extractor. 

The if condition is now _if (letter.Location.Y < (y.Value - 0.5))_ and before leaving the foreach loop I'm updating the y value with _y = letter.Location.Y_ which is copied from previous _if_ block.

These changes are because I have a series of letters where a period character is directly above some other text. The y values mean they're on different lines but the x values when checked suggest that they could be next to each other like this:

.
 Mech

I hope this helps and is clear.

Also, great work!

**Comment by EliotJones** [comment]
Thanks for the great advice @johnsharp1975.

I have updated the first part but I'm not sure on the dynamic updating of the `y` value in the loop. It could make sense but I think the current behaviour is basically intended to 'anchor' the current line to the first letter selected rather than update per-letter. I'm not sure it makes a huge difference either way but this change starts with making sure the `y` value is checked as intended firstly and I'll think on the other suggested change.

**Comment by Aldaviva** [comment]
I had also encountered this. Great to see an upstream fix get released before I could even report it! Thanks all.
