### ISSUE TITLE
PdfPig says letters are black, but text is invisible

### ISSUE THREAD

**Issue by Hert79** [UglyToad/PdfPig#622]
[HiddenText.pdf](https://github.com/UglyToad/PdfPig/files/11450834/HiddenText.pdf)
There appears to be no text on this page, but PdfPig does return some TextBlocks and DocumentLayoutAnalyis confirms the text is within the page's cropbox:
![image](https://github.com/UglyToad/PdfPig/assets/54370640/985674e0-c67a-486b-a493-4633e1bd3094)

however PdfPig returns the letters as having color RGB{1:1:1} which is black. There are no images on top of the text.
![image](https://github.com/UglyToad/PdfPig/assets/54370640/095919f0-26b6-426a-86c6-91cffa973f0a)

How can I detect that this text is in fact invisible?
Tested this with the latest prerelease.

**Comment by BobLd** [comment]
Hi @Hert79, if you display the paths in the DlaViewer, you will see the invisible text you are refering to is outside the clipping path.

I'm pretty sure that explains why this text will not be rendered (even if the text is black) as only what's inside the clipping path should be painted.

PdfPig does not support clipping for letters at the moment (it does for paths), but this is something I might look into soon.

![image](https://github.com/UglyToad/PdfPig/assets/38405645/2ff16dd3-2d5c-427d-a559-54ee80904529)

**A note about clipping path:** For the moment, there is no way to check that this particular clipping path is actually related to the invisible text (but because this document example is very simple, this is most certainly the case). In more complex documents, it might be difficult to link letters to their clipping path.

I think this is where the check for inside or outside of clipping path should be done for text (really not sure though):
https://github.com/UglyToad/PdfPig/blob/3898f09a5f9447c68204d0e5fc238f19d082c028/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs#LL226C8-L230C18

As an fyi, this is where the path are clipped
https://github.com/UglyToad/PdfPig/blob/3898f09a5f9447c68204d0e5fc238f19d082c028/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs#LL759C9-L759C32

**Comment by BobLd** [comment]
Clipping letters now supported via #905
