### ISSUE TITLE
Page.Letters is empty for document which contains text

### ISSUE THREAD

**Issue by adg-mh** [UglyToad/PdfPig#73]
Using attached document and program below nothing is written to the console. Sample PDF came from a commercial HTML to PDF library one of our customers uses.

[Getting_Started.pdf](https://github.com/UglyToad/PdfPig/files/3731628/Getting_Started.pdf)

```
using System;
using UglyToad.PdfPig;

namespace ExtractTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using (PdfDocument document = PdfDocument.Open("Getting_Started.pdf"))
            {
                for (var i = 0; i < document.NumberOfPages; i++)
                {
                    var page = document.GetPage(i + 1);
                    foreach (var letter in page.Letters)
                    {
                        Console.WriteLine(letter.Value);
                    }
                }
            }
        }
    }
}
```

**Comment by EliotJones** [comment]
This is because the content of this document is using PostScript form XObjects. This won't actually make a difference to how the content should be consumed through the API it's just something I haven't implemented yet because this is only the 2nd ever time I've seen content encoded in this way: https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig.Tests/Integration/SinglePageFormContentIText1Tests.cs#L37

I'll try to get round to adding support for this before the end of the week.

**Comment by adg-mh** [comment]
I can confirm I now get text content. Thank you for the quick fix.
