### ISSUE TITLE
[Proposal] Replace IList<byte> with ReadOnlySpan<byte> & ReadOnlyMemory<byte>

### ISSUE THREAD

**Issue by iamcarbon** [UglyToad/PdfPig#810]
I've started exploring whether we can replace our use of List with ReadOnlySpan<byte> / ReadOnlyMemory<byte> to eliminate virtual calls, enable vectorized operations (since this would force everything to linear memory), and reduce various intermediate allocations using slices of the original PDF.

It looks like this is possible and will result in a notable performance improvement -- but will end up effectively nearly every part of the PDF pipeline (filters, decoding, encoding, etc).

Unfortunately, due to the tight coupling between components, it looks like we would need to change nearly everything at once to enable this change, so the data can flow through the entire pipeline.

I wanted to start an issue before continuing this exploration, and get everyone's thoughts on the resulting breaking changes.

Generally, any use of IList<byte> would become either ReadOnlyMemory<byte> or ReadOnlySpan<byte>, depending on the methods scope and lifetime.

As this is a major change, and will involve a fair amount of work -- I'd love to hear what everyone thinks before posting a possible PR.

CC @BobLd

**Comment by BobLd** [comment]
@iamcarbon on my side, this is an improvement I'd really like. I had a look at that recently and I confirm this will be a wide change (I stopped due to lack of time).

I think this is the perfect time to do this change as version .0.9 already has many breaking changes.

Just want to confirm @EliotJones is good to go in that direction. If good, I'll review the PR with great pleasure 

Thanks again for your hard work
