### ISSUE TITLE
Populate data catalog info without reading the rest of the pdf

### ISSUE THREAD

**Issue by bdurrani** [UglyToad/PdfPig#869]
Hello

First of all, thanks for this great library

My use case for this library is to figure out how many pages are present in the PDF, and nothing else. I've run into a scenario where certain PDFs take a long time to load because of corrupted xrefs, which triggers a brute force search for reference objects. Stuff that I dont really have any need for. The PDF does eventually load, but it takes a while.
Unfortunately I am unable to share the PDF, but I know it has a bad xref table. 

I was wondering if it's possible to introduce some kind of lazy loading, such that only properties that are found in the File trailer, and maybe the document catalog are loaded as part of opening the document. And the rest of the loading process can be delayed till an explicit call to load is made. 

I was digging around the code to figure out how the page count happens, but there is a lot of complexity with the xref streams being introduced with PDF v1.5. I'm not very familiar with the PDF specification, but it seems like it's possible to get a lot of this kind of information without processing the entire pdf. But I might be wrong.

I realize this is a very specific use case, but would appreciate any thoughts you might have about it. 

Thanks for your consideration.

**Comment by EliotJones** [comment]
It has been a long time since I wrote any code for this project but from what I vaguely recall the page count isn't available without traversing the tree of page objects.

In order to traverse the tree you need to have populated the list of objects by their offset in the file which involves recovering from corrupted xrefs with brute force scanning.

> Pages dictionary (Required; must be an indirect reference) The page tree node that is the root of the document’s page tree

In your case there are probably things PdfPig does that slow execution down more than is necessary since it is optimised (or rather... deoptimised) for document text extraction use-cases. I'd suggest checking if the LGPL version of iTextSharp might be more performant in this case since I think they tend to work at a lower-level, closer to the bare-bones document structure.

https://www.nuget.org/packages/iTextSharp.LGPLv2.Core

**Comment by bdurrani** [comment]
Hi Eliot

I'll check out the link. Although we've moved on from the problem so not sure when I'll revisit this again.
I'll close out this issue.

Thanks for the response.
