### ISSUE TITLE
Bounding Box Misalignment with Word 'Print as PDF'

### ISSUE THREAD

**Issue by acmitch** [UglyToad/PdfPig#885]
I've spent some time troubleshooting a misalignment issue and discovered that it occurs when a document is exported from Microsoft Word using the "Print as PDF" feature. The bounding boxes for the text appear to be both upside down and incorrectly scaled.

I've attached a screenshot of a document exported with the "Print to PDF" functionality to illustrate the issue. To reproduce this, simply open Word, paste some text, and use the "Print as PDF" option. The text in the document parses correctly, but the bounding boxes are inverted and incorrectly scaled for each block and word. In the image below, you can see that Block 0, which should be at the top, is instead at the bottom of the page and upside down. This issue is consistent across all blocks. I also confirmed that the page has no rotation set when processed.

Note, that if I export or save the file directly as a PDF everything works as expected.

[The Rover - Print to PDF.pdf](https://github.com/user-attachments/files/16817793/The.Rover.-.Print.to.PDF.pdf)

![image](https://github.com/user-attachments/assets/ee982dd9-79f3-4745-9580-badaabed1086)

**Comment by BobLd** [comment]
@acmitch do you mind sharing the code you use the draw the bounding boxes? I don't see obvious issue so far

**Comment by acmitch** [comment]
@BobLd sure you can replicate with the below code. 

I should mention that the processing on my end seems to be working as expected, with words being processed correctly. However, the output is not as expected. I've attached a screenshot of the run below the code snippet.

```
<PackageReference Include="PdfPig" Version="0.1.8" />
```

```csharp
var userDirectory = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
var sourcePdfPath = Path.Combine(userDirectory, "Downloads", "The.Rover.-.Print.to.PDF.pdf");
var outputPath = Path.Combine(userDirectory, "Downloads", "PdfPig-Output.pdf");

const int pageNumber = 1;

using var document = PdfDocument.Open(sourcePdfPath);
var page = document.GetPage(pageNumber);

var letters = page.Letters; // no preprocessing

// 1. Extract words
var wordExtractor = new NearestNeighbourWordExtractor();
var words = wordExtractor.GetWords(letters).ToList();
    
// 2. Segment page
var pagePartitioner = DocstrumBoundingBoxes.Instance;
var textBlocks = pagePartitioner.GetBlocks(words);

// 3. Postprocessing
var readingOrder = UnsupervisedReadingOrderDetector.Instance;
var orderedTextBlocks = readingOrder.Get(textBlocks);
    
// 4. Visualize Bounding boxes
var builder = new PdfDocumentBuilder();
var font = builder.AddStandard14Font(Standard14Font.Helvetica);
var pageBuilder = builder.AddPage(document, pageNumber);
pageBuilder.SetRotation(page.Rotation);

foreach (var textBlock in orderedTextBlocks)
{
    pageBuilder.SetStrokeColor(0, 255, 0);
    pageBuilder.SetTextAndFillColor(0, 255, 0);
    
    // draw text block lines 
    var textBbox = textBlock.BoundingBox;
    pageBuilder.DrawRectangle(textBbox.BottomLeft, (decimal)textBbox.Width, (decimal)textBbox.Height);
    pageBuilder.AddText(textBlock.ReadingOrder.ToString(), 8, textBbox.Centroid, font);
    
    pageBuilder.SetStrokeColor(255, 0, 0);
    
    // draw word lines 
    foreach (var textLine in textBlock.TextLines)
    {
        foreach (var block in textLine.Words)
        {
            var bbox = block.BoundingBox;
            pageBuilder.DrawRectangle(bbox.BottomLeft, (decimal)bbox.Width, (decimal)bbox.Height);
        }
    }
}

// 5. Write result to a file
var fileBytes = builder.Build();
File.WriteAllBytes(outputPath, fileBytes);
```

Input: [The.Rover.-.Print.to.PDF.pdf](https://github.com/user-attachments/files/16825088/The.Rover.-.Print.to.PDF.pdf)
Output: [PdfPig-Output.pdf](https://github.com/user-attachments/files/16825089/PdfPig-Output.pdf)

**Comment by acmitch** [comment]
If I copy the content from the PDF into Word and then use "Save As" to create a new PDF, it works correctly.

Input: [TheRover-SaveToPdf.pdf](https://github.com/user-attachments/files/16825111/TheRover-SaveToPdf.pdf)
Output: [PdfPig-Output2.pdf](https://github.com/user-attachments/files/16825113/PdfPig-Output2.pdf)

**Comment by BobLd** [comment]
@acmitch will try to find time to look into it today but in the meantime, do you mind trying with the latest pre-release version 0.1.9?

**Comment by acmitch** [comment]
@BobLd no luck. I gave it a run with `0.1.9-alpha-20240821-b4649` but same result.

**Comment by BobLd** [comment]
@acmitch I had a look at your problem, and the bug is *not* related to the bounding boxes / text.

The issue is linked to the transformation matrix:

On `builder.AddPage(document, pageNumber)` the page's transformation matrix is set to the original document's matrix `[0.75, 0, 0, -0.75, 0, 792]`

You then draw the bounding boxes, but they are transformation matrix independent (i.e. their position are in the identity transformation matrix).

So, before drawing the bounding boxes, the transformation matrix of the page needs to be reset to the identity:

```csharp
[...]
pageBuilder.SetRotation(page.Rotation);

var m = TransformationMatrix.FromArray([0.75, 0, 0, -0.75, 0, 792]).Inverse();
var cm = new ModifyCurrentTransformationMatrix([m.A, m.B, m.C, m.D, m.E, m.F]);
pageBuilder.CurrentStream.Operations.Add(cm);

foreach (var textBlock in orderedTextBlocks)
[...]
```

Now, I think this is a bug as I don't think this is up to the end user to reset the matrix to the identity: the transformation matrix should be reset at the end of `builder.AddPage(document, pageNumber)` method call.


I don't know enough about the `PdfDocumentBuilder` to be able to push a fix yet. Happy for you to look into it

**Comment by acmitch** [comment]
@BobLd, thanks for the helpful information. Could you clarify this part of your comment:

‘You then draw the bounding boxes, but they are transformation matrix independent (i.e., their positions are in the identity transformation matrix).’

Why would the bounding boxes be independent of the transformation matrix? Is it because the add page method applies all transformations first, so by the time I draw the boxes, the page transformation has already occurred, causing the bounding box positions to be incorrect due to applying them out of order?

**Comment by BobLd** [comment]
Let's forget for a moment the `PdfDocumentBuilder`: When the bounding boxes in the page are extracted, they already have the transformation matrix applied to them. I said "transformation matrix independent" because the end user does not need to know what was the transformation matrix at the time the letters were drawn.

Now, you want to draw the bounding boxes in an existing pdf page. Your pdf page has a transformation matrix `[0.75, 0, 0, -0.75, 0, 792]`. All the operations done on the existing page take in account this transformation matrix.

When you draw your bounding boxes, you draw them with this transformation matrix still being the "current transformation matrix", meaning the coordinates of the bounding boxes will be transformed using this matrix. But remember, these bounding boxes already have the matrix applied to them from the extraction step.

In order to correctly display these boxes, the current transformation matrix (`[0.75, 0, 0, -0.75, 0, 792]`) needs to be reset to the identity matrix (no transformation). This is the code snippet I shared.

I hope this is a bit more clear

**Comment by acmitch** [comment]
@BobLd I understand now. It seems this behavior is expected, given that applying the identity matrix is primarily for drawing bounding boxes. I’ll handle this on the client side, following your example. It might be worth considering adding a dedicated method to the builder for drawing bounding boxes, which could handle applying the identity matrix and then resetting back to the transformation matrix. Thanks again!
